# Site settings
title: Bhavir Shah
email: shahbhavir@gmail.com
description: "An Enthusiast"
baseurl: ""
url: "http://shahbhavir.github.io"
twitter_username: shahbhavir
github_username: shahbhavir
facebook_username: shahbhavir

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
